services:
  nginx:
    container_name: nginx-server
    image: nginx:latest
    tty: true
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80